### ISSUE TITLE
In Mathematica 11.2 some exported video files appear to be damaged and don't load properly

### ISSUE THREAD

**Issue by Helyk** [kmisiunas/ffmpeg-mathematica#6]
![image](https://user-images.githubusercontent.com/33000559/36974708-6a6de8d2-2099-11e8-98ed-d9e82f9b327f.png)
Hello. I'm getting the above error when trying to `FFImport` frames from a video that was created like this:
```Mathematica
Run["ffmpeg -i \"" <> inputFileName <> "\" -vf \"pp=l5,rotate=" <> ToString[-Round[angle, 0.1]] <> "*PI/180:ow=rotw(" <> ToString[-Round[angle, 0.1]] <> "*PI/180):oh=roth(" <> ToString[-Round[angle, 0.1]] <> "*PI/180)\" -c:v mjpeg -qscale:v 3 \"" <> outputFileName <> "\" -y"]
```

This error appears on Windows 10.0.16299.192 x64 with Mathematica 11.2 and ffmpeg [ffmpeg version.txt](https://github.com/kmisiunas/ffmpeg-mathematica/files/1781528/ffmpeg.version.txt). Whether this error appears or not, sometimes depends on value of `angle`, for example it may work fine with 316 but not with 318. Also, for damaged video files, preview is not generated by Windows Explorer. However, my video player opens those files without errors or warnings.
The problem appeared when I updated to Mathematica 11.2.
Both input and output files are .MOV but I also tried .avi output and got the same error.

I'm not sure if this error is caused by FFmpeg.m. Maybe it is caused by something else, like ffmpeg itself or by Mathematica. I would appreciate any ideas on diagnostics.

**Comment by Helyk** [comment]
It seems that the error may be observed when attempting to do the following:
```Mathematica
FFImport[outputFileName, "FrameCount"]
```
rather than when importing specific frames.

**Comment by kmisiunas** [comment]
Hi. Are you running the latest version of ffmpeg-mathematica? 
There was an issue, where `FFImport[outputFileName, "FrameCount"]` would use Mathematica's inbuilt `FrameCount` function. This inbuilt function was unable to open many of the video files. I think I fixed this issue few months ago

**Comment by Helyk** [comment]
Thanks for your advice. It seems that the latest version of ffmpeg-mathematica does not produces this error. I will take some time to do more tests and will close the issue if everything works fine.
